In [ ]:
# Create a vector
my_vector <- c(1, 2, 3, 4, 5)
print(my_vector)


[1] 1 2 3 4 5


In [ ]:
# Generate sequences
my_seq <- seq(1, 10, by = 2)
print(my_seq)


[1] 1 3 5 7 9


In [ ]:
# Repeat elements
my_rep <- rep(1:3, times = 2)
print(my_rep)

[1] 1 2 3 1 2 3


In [ ]:
# Get vector length
len <- length(my_vector)
print(len)

[1] 5


In [ ]:
# Sort values
sorted_vec <- sort(c(5, 3, 8, 1))
print(sorted_vec)

[1] 1 3 5 8


In [ ]:
# Get ordering index
order_idx <- order(c(5, 3, 8, 1))
print(order_idx)

[1] 4 2 1 3


In [ ]:
# Reverse elements
reversed_vec <- rev(c(1, 2, 3, 4, 5))
print(reversed_vec)

[1] 5 4 3 2 1


In [ ]:
# Find unique values
unique_vals <- unique(c(1, 2, 2, 3, 4, 4))
print(unique_vals)

[1] 1 2 3 4


In [ ]:
# Frequency table
freq_table <- table(c(1, 2, 2, 3, 3, 3))
print(freq_table)


1 2 3 
1 2 3 


In [ ]:
# Find indices of matching values
match_idx <- match(2, c(1, 2, 3, 4))
print(match_idx)

[1] 2


In [ ]:
# Check if value exists in vector
exists <- 2 %in% c(1, 2, 3, 4)
print(exists)

[1] TRUE


In [ ]:
# Find index of elements satisfying a condition
which_vec <- which(c(1, 2, 3, 4) > 2)
print(which_vec)

[1] 3 4


In [ ]:
#  Check if any value is TRUE
any_true <- any(c(FALSE, TRUE, FALSE))
print(any_true)

[1] TRUE


In [ ]:
# Check if all values are TRUE
all_true <- all(c(TRUE, TRUE, TRUE))
print(all_true)

[1] TRUE


In [ ]:
# Check for missing values
missing_vals <- is.na(c(1, 2, NA, 4))
print(missing_vals)

[1] FALSE FALSE  TRUE FALSE


In [ ]:
#  Remove NA values
clean_vec <- na.omit(c(1, 2, NA, 4))
print(clean_vec)

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"


In [ ]:
#  Replace values in a vector
replaced_vec <- replace(c(1, 2, 3), 2, 10)
print(replaced_vec)

[1]  1 10  3


In [ ]:
#  Concatenate strings
concatenated <- paste("Hello", "World")
print(concatenated)

[1] "Hello World"


In [ ]:
# Concatenate without spaces
concatenated_no_space <- paste0("Hello", "World")
print(concatenated_no_space)

[1] "HelloWorld"


In [ ]:
# Convert to uppercase
upper_str <- toupper("hello")
print(upper_str)

[1] "HELLO"


In [ ]:
# Convert to lowercase
lower_str <- tolower("HELLO")
print(lower_str)

[1] "hello"


In [ ]:
# Extract substring
substring_str <- substr("Hello World", 1, 5)
print(substring_str)

[1] "Hello"


In [ ]:
# Pattern matching
grep_result <- grep("hello", c("hello", "world", "hello world"))
print(grep_result)

[1] 1 3


In [ ]:
# Replace pattern
replaced_str <- gsub("hello", "hi", "hello world")
print(replaced_str)

[1] "hi world"


In [ ]:
# Split strings
split_str <- strsplit("Hello World", " ")
print(split_str)

[[1]]
[1] "Hello" "World"



In [ ]:
# Convert to numeric
numeric_val <- as.numeric("123.45")
print(numeric_val)

[1] 123.45


In [ ]:
# Convert to character
char_val <- as.character(123)
print(char_val)

[1] "123"


In [ ]:
# Convert to factor
factor_val <- as.factor(c("low", "medium", "high"))
print(factor_val)

[1] low    medium high  
Levels: high low medium


In [ ]:
#  Convert to date
date_val <- as.Date("2025-02-03")
print(date_val)

[1] "2025-02-03"


In [ ]:
# Get current date
current_date <- Sys.Date()
print(current_date)

[1] "2025-02-03"


In [ ]:
# Sum of elements
total_sum <- sum(c(1, 2, 3, 4, 5))
print(total_sum)

[1] 15


In [ ]:
# Product of elements
total_prod <- prod(c(1, 2, 3, 4, 5))
print(total_prod)

[1] 120


In [ ]:
# Cumulative sum
cum_sum <- cumsum(c(1, 2, 3, 4, 5))
print(cum_sum)

[1]  1  3  6 10 15


In [ ]:
# Cumulative product
cum_prod <- cumprod(c(1, 2, 3, 4, 5))
print(cum_prod)

[1]   1   2   6  24 120


In [ ]:
# Compute mean
avg <- mean(c(1, 2, 3, 4, 5))
print(avg)

[1] 3


In [ ]:
#  Compute median
med <- median(c(1, 2, 3, 4, 5))
print(med)

[1] 3


In [ ]:
# Find minimum
min_val <- min(c(5, 3, 8, 1))
print(min_val)

[1] 1


In [ ]:
#  Find maximum
max_val <- max(c(5, 3, 8, 1))
print(max_val)

[1] 8


In [ ]:
# Find range (min and max values)
range_vals <- range(c(5, 3, 8, 1))
print(range_vals)

[1] 1 8


In [ ]:
# Variance
variance_val <- var(c(1, 2, 3, 4, 5))
print(variance_val)

[1] 2.5


In [ ]:
# Standard deviation
std_dev <- sd(c(1, 2, 3, 4, 5))
print(std_dev)

[1] 1.581139


In [ ]:
# Compute quantiles
quartiles <- quantile(c(1, 2, 3, 4, 5), probs = c(0.25, 0.5, 0.75))
print(quartiles)

25% 50% 75% 
  2   3   4 


In [ ]:
# Round values
rounded_val <- round(3.14159, digits = 2)
print(rounded_val)

[1] 3.14


In [ ]:
# Round up
ceil_val <- ceiling(3.14)
print(ceil_val)

[1] 4


In [ ]:
# Round down
floor_val <- floor(3.99)
print(floor_val)

[1] 3


In [ ]:
#  Absolute value
abs_val <- abs(-10)
print(abs_val)

[1] 10


In [ ]:
# Square root
sqrt_val <- sqrt(16)
print(sqrt_val)

[1] 4


In [ ]:
# Natural logarithm
log_val <- log(10)
print(log_val)

[1] 2.302585


In [ ]:
# Exponential function
exp_val <- exp(2)
print(exp_val)

[1] 7.389056


In [ ]:
# Compute factorial
fact_val <- factorial(5)
print(fact_val)

[1] 120


In [ ]:
# Compute binomial coefficient (nCr)
binom_coeff <- choose(5, 2)
print(binom_coeff)

[1] 10


In [ ]:
# Sine function
sin_val <- sin(pi / 2)
print(sin_val)

[1] 1


In [ ]:
# Cosine function
cos_val <- cos(pi)
print(cos_val)

[1] -1


In [ ]:
# Tangent function
tan_val <- tan(pi / 4)
print(tan_val)

[1] 1


In [ ]:
#  Correlation coefficient
cor_val <- cor(c(1, 2, 3), c(4, 5, 6))
print(cor_val)

[1] 1


In [ ]:
# Covariance
cov_val <- cov(c(1, 2, 3), c(4, 5, 6))
print(cov_val)

[1] 1


In [ ]:
#  Create a data frame

In [ ]:
#  Create a data frame
df <- data.frame(Name = c("Alice", "Bob"), Age = c(25, 30))
print(df)

   Name Age
1 Alice  25
2   Bob  30


In [ ]:
# Create a list
my_list <- list(Name = "Alice", Age = 25, Scores = c(80, 90, 85))
print(my_list)

$Name
[1] "Alice"

$Age
[1] 25

$Scores
[1] 80 90 85



In [ ]:
# Create a matrix
mat <- matrix(1:9, nrow = 3, ncol = 3)
print(mat)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
# Create an array
arr <- array(1:12, dim = c(2, 3, 2))
print(arr)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12



In [ ]:
# Transpose a matrix
transposed_mat <- t(mat)
print(transposed_mat)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [ ]:
# Row bind data
df2 <- rbind(df, data.frame(Name = "Charlie", Age = 28))
print(df2)

     Name Age
1   Alice  25
2     Bob  30
3 Charlie  28


In [ ]:
#  Column bind data
df3 <- cbind(df, Salary = c(50000, 55000))
print(df3)

   Name Age Salary
1 Alice  25  50000
2   Bob  30  55000


In [ ]:
# Get dimensions of matrix/dataframe
dimensions <- dim(df)
print(dimensions)

[1] 2 2


In [ ]:
# Number of rows
rows <- nrow(df)
print(rows)

[1] 2


In [ ]:
# Number of columns
cols <- ncol(df)
print(cols)

[1] 2


In [ ]:
# Get or set column names
col_names <- names(df)
names(df) <- c("Full_Name", "Age_Years")
print(col_names)

[1] "Name" "Age" 


In [ ]:
# Get/set column names
colnames(df) <- c("Name", "Age")
print(colnames)

function (x, do.NULL = TRUE, prefix = "col") 
{
    if (is.data.frame(x) && do.NULL) 
        names(x)
    else dimnames(x)[[2L]] %||% if (do.NULL) 
        NULL
    else {
        nc <- NCOL(x)
        if (nc > 0L) 
            paste0(prefix, seq_len(nc))
        else character()
    }
}
<bytecode: 0x59280f1bf258>
<environment: namespace:base>


In [ ]:
# Get/set row names
rownames(df) <- c("Row1", "Row2")
print(rownames)

function (x, do.NULL = TRUE, prefix = "row") 
{
    dimnames(x)[[1L]] %||% if (do.NULL) 
        NULL
    else {
        nr <- NROW(x)
        if (nr > 0L) 
            paste0(prefix, seq_len(nr))
        else character()
    }
}
<bytecode: 0x592810070b80>
<environment: namespace:base>


In [ ]:
#  Subset data
sub_df <- subset(df, Age > 25)
print(sub_df)

     Name Age
Row2  Bob  30


In [ ]:
# Merge data frames
df4 <- data.frame(Name = c("Alice", "Bob"), Salary = c(60000, 65000))
merged_df <- merge(df, df4, by = "Name")
print(df4)

   Name Salary
1 Alice  60000
2   Bob  65000


In [ ]:
# Apply function over array margins
row_sums <- apply(mat, 1, sum)  # Sum each row
print(row_sums)

[1] 12 15 18


In [ ]:
# Apply function over list (returns list)
lapply_result <- lapply(list(1:5, 6:10), sum)
print(lapply_result)

[[1]]
[1] 15

[[2]]
[1] 40



In [ ]:
# Simplified apply over list (returns vector/matrix)
sapply_result <- sapply(list(1:5, 6:10), sum)
print(sapply_result)

[1] 15 40


In [ ]:
# Apply function over subsets
tapply_result <- tapply(c(10, 20, 30, 40), c("A", "A", "B", "B"), sum)
print(tapply_result)

 A  B 
30 70 


In [ ]:
# Aggregate data
df5 <- data.frame(Group = c("A", "A", "B", "B"), Score = c(10, 20, 30, 40))
agg_df <- aggregate(Score ~ Group, data = df5, FUN = mean)
print(df5)

  Group Score
1     A    10
2     A    20
3     B    30
4     B    40


In [ ]:
# Split data into groups
split_data <- split(df5$Score, df5$Group)
print(split_data)

$A
[1] 10 20

$B
[1] 30 40



In [ ]:
# Convert dataframe columns into key-value pairs
df6 <- data.frame(A = c(1, 2), B = c(3, 4))
stacked_df <- stack(df6)
print(df6)

  A B
1 1 3
2 2 4


In [ ]:
# Convert stacked data back
unstacked_df <- unstack(stacked_df)
print(unstacked_df)

  A B
1 1 3
2 2 4


In [ ]:
# Reshape data
df7 <- data.frame(ID = c(1, 1, 2, 2), Time = c(1, 2, 1, 2), Value = c(10, 20, 15, 25))
reshaped_df <- reshape(df7, idvar = "ID", timevar = "Time", direction = "wide")
print(df7)

  ID Time Value
1  1    1    10
2  1    2    20
3  2    1    15
4  2    2    25


In [ ]:
#   Vectorized conditional statement
x <- c(1, 5, 10, 15)
result <- ifelse(x > 5, "Greater than 5", "Less or equal to 5")
print(result)

[1] "Less or equal to 5" "Less or equal to 5" "Greater than 5"    
[4] "Greater than 5"    


In [ ]:
# Conditional execution
x <- 10
if (x > 5) {
    print("x is greater than 5")
}


[1] "x is greater than 5"


In [ ]:
# Alternative branch for if
x <- 3
if (x > 5) {
    print("x is greater than 5")
} else {
    print("x is 5 or less")
}


[1] "x is 5 or less"


In [ ]:
# Loop over sequence
for (i in 1:5) {
    print(paste("Iteration:", i))
}


[1] "Iteration: 1"
[1] "Iteration: 2"
[1] "Iteration: 3"
[1] "Iteration: 4"
[1] "Iteration: 5"


In [ ]:
# Loop while condition holds
x <- 1
while (x <= 5) {
    print(paste("x is:", x))
    x <- x + 1
}


[1] "x is: 1"
[1] "x is: 2"
[1] "x is: 3"
[1] "x is: 4"
[1] "x is: 5"


In [ ]:
# Infinite loop (until break)
x <- 1
repeat {
    print(x)
    x <- x + 1
    if (x > 5) {
        break
    }
}



[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
# Exit loop
for (i in 1:10) {
    if (i == 5) {
        break  # Exit loop when i is 5
    }
    print(i)
}


[1] 1
[1] 2
[1] 3
[1] 4


In [ ]:
#  Skip current iteration
for (i in 1:5) {
    if (i == 3) {
        next  # Skip printing when i is 3
    }
    print(i)
}


[1] 1
[1] 2
[1] 4
[1] 5


In [ ]:
# Define a function
add_numbers <- function(a, b) {
    return(a + b)
}
result <- add_numbers(3, 5)
print(result)


[1] 8


In [ ]:
# Return value from function
multiply_numbers <- function(a, b) {
    return(a * b)
}
result <- multiply_numbers(4, 5)
print(result)


[1] 20


In [ ]:
#  Halt execution with error
check_positive <- function(x) {
    if (x < 0) {
        stop("Error: x must be positive")
    }
    return(sqrt(x))
}
check_positive(5)


[1] 2.236068

In [ ]:
# Generate a warning message
check_age <- function(age) {
    if (age < 18) {
        warning("Warning: You are under 18!")
    }
    return(paste("Age is", age))
}
check_age(16)


Warning message in check_age(16):
“Warning: You are under 18!”


[1] "Age is 16"

In [ ]:
# Catch errors (prevents stopping execution)
result <- try(log("a"))  # Attempting to take log of a character
print("Code continues even if an error occurs")


Error in log("a") : non-numeric argument to mathematical function
[1] "Code continues even if an error occurs"


In [ ]:
# Advanced error handling
safe_log <- function(x) {
    tryCatch({
        log(x)
    }, error = function(e) {
        print("Error caught: Returning NA")
        return(NA)
    })
}
result1 <- safe_log(10)  # Works fine
result2 <- safe_log("a") # Catches error and returns NA


[1] "Error caught: Returning NA"


In [ ]:
# Working with Directories

In [ ]:
# Get current working directory
current_dir <- getwd()
print(current_dir)


[1] "/content"


In [ ]:
# Set working directory
setwd("C:/Users/YourName/Documents")  # Change to your desired path


In [ ]:
# List files in directory
files <- list.files()
print(files)


[1] "sample_data"


In [ ]:
# Check if a file exists
file.exists("Fortune 500 Companies.csv")

[1] TRUE

In [ ]:
# Delete a file
file.remove("data.csv")

Warning message in file.remove("data.csv"):
“cannot remove file 'data.csv', reason 'No such file or directory'”


[1] FALSE

In [ ]:
# Read CSV file
data <- read.csv("Fortune 500 Companies.csv")
print(head(data))

                                         name rank year
1                  General Motors Corporation    1 1996
2                          Ford Motor Company    2 1996
3                           Exxon Corporation    3 1996
4                       Wal-Mart Stores, Inc.    4 1996
5                                  AT&T Corp.    5 1996
6 International Business Machines Corporation    6 1996
                     industry sector headquarters_state headquarters_city
1      Motor Vehicles & Parts                        MI                  
2      Motor Vehicles & Parts                        MI                  
3          Petroleum Refining                        TX                  
4       General Merchandisers                        AR                  
5          Telecommunications                        NY                  
6 Computers, Office Equipment                        NY                  
  market_value_mil revenue_mil profit_mil asset_mil employees founder_is_ceo
1            

In [ ]:
# Write CSV file
df <- data.frame(Name = c("Alice", "Bob"), Age = c(25, 30))
write.csv(df, "output.csv", row.names = FALSE)


In [ ]:
#  Read tabular data (with space or tab separators)
data_table <- read.table("data.txt", header = TRUE)


In [ ]:
# Write tabular data
write.table(df, "output.txt", row.names = FALSE, sep = "\t")


In [ ]:
#  Read R object from file
my_data <- readRDS("data.rds")


Warning message in gzfile(file, "rb"):
“cannot open compressed file 'data.rds', probable reason 'No such file or directory'”


ERROR: Error in gzfile(file, "rb"): cannot open the connection


In [ ]:
# Save R object to file
saveRDS(df, "data.rds")  # Save the dataframe as an RDS file



In [ ]:
# working with factors

In [ ]:
# Create a factor variable
colors <- factor(c("Red", "Blue", "Green", "Red", "Blue"))
print(colors)


[1] Red   Blue  Green Red   Blue 
Levels: Blue Green Red


In [ ]:
# Get/set levels of a factor
levels(colors)
levels(colors) <- c("Blue", "Green", "Red")
print(colors)


[1] "Blue"  "Green" "Red"

[1] Red   Blue  Green Red   Blue 
Levels: Blue Green Red


In [ ]:
# Reorder factor levels (set a reference level)
colors <- relevel(colors, ref = "Green")  # Set "Green" as the first level
print(colors)


[1] Red   Blue  Green Red   Blue 
Levels: Green Blue Red


In [ ]:
# Convert numeric data into factor bins
ages <- c(10, 25, 40, 55, 70)
age_groups <- cut(ages, breaks = c(0, 18, 35, 50, 100),
                  labels = c("Child", "Young Adult", "Adult", "Senior"))
print(age_groups)


[1] Child       Young Adult Adult       Senior      Senior     
Levels: Child Young Adult Adult Senior


In [ ]:
# time handling in r

In [ ]:
# Convert to date-time format
datetime_ct <- as.POSIXct("2024-02-03 14:30:00")
print(datetime_ct)


[1] "2024-02-03 14:30:00 UTC"


In [ ]:
# Convert to list-like date format
datetime_lt <- as.POSIXlt("2024-02-03 14:30:00")
print(datetime_lt$year + 1900)  # Extract year
print(datetime_lt$hour)  # Extract hour


[1] 2024
[1] 14


In [ ]:
# Compute time difference
start_time <- as.POSIXct("2024-02-03 12:00:00")
end_time <- as.POSIXct("2024-02-03 15:30:00")
time_diff <- difftime(end_time, start_time, units = "hours")
print(time_diff)


Time difference of 3.5 hours


In [ ]:
# Format dates
formatted_date <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
print(formatted_date)


[1] "2025-02-03 15:35:36"


In [ ]:
# managing objects in environment

In [ ]:
# List objects in the environment
x <- 10
y <- "Hello"
z <- c(1, 2, 3)
print(ls())  # List all objects


 [1] "add_numbers"      "age_groups"       "ages"             "check_age"       
 [5] "check_positive"   "colors"           "current_dir"      "data"            
 [9] "datetime_ct"      "datetime_lt"      "end_time"         "files"           
[13] "formatted_date"   "i"                "multiply_numbers" "result"          
[17] "result1"          "result2"          "safe_log"         "start_time"      
[21] "time_diff"        "x"                "y"                "z"               


In [ ]:
# Remove objects
rm(x)  # Remove object x
print(ls())  # Verify x is removed


 [1] "add_numbers"      "age_groups"       "ages"             "check_age"       
 [5] "check_positive"   "colors"           "current_dir"      "data"            
 [9] "datetime_ct"      "datetime_lt"      "end_time"         "files"           
[13] "formatted_date"   "i"                "multiply_numbers" "result"          
[17] "result1"          "result2"          "safe_log"         "start_time"      
[21] "time_diff"        "y"                "z"               


In [ ]:
# Perform garbage collection
gc()  # Free up memory


used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  712692 38.1 1437941    76.8 1437941  76.8
Vcells 1570609 12.0 8388608    64.0 3115359  23.8

In [ ]:
# debugging functions

In [ ]:
#  Debug a function
my_function <- function(x) {
    y <- x + 10
    return(y)
}
debug(my_function)  # Enable debugging
my_function(5)  # Runs in debug mode


debugging in: my_function(5)
debug: {
    y <- x + 10
    return(y)
}
debug: y <- x + 10
debug: return(y)
exiting from: my_function(5)


[1] 15

In [ ]:
# Show call stack after error
error_function <- function() {
    stop("This is an error")
}
error_function()  # Causes an error
traceback()  # Shows the call stack


ERROR: Error in error_function(): This is an error


In [ ]:
# Print output
message <- "Hello, world!"
print(message)


[1] "Hello, world!"


In [ ]:
# Print text output (better for formatted output)
name <- "Alice"
age <- 25
cat("Name:", name, "\nAge:", age, "\n")


Name: Alice 
Age: 25 
