<a href="https://colab.research.google.com/github/narendra7959/R-Practicals/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Data Structures in R**

In [1]:
# Narendra
# Reg No : 24040208002

**Vectors**

In [ ]:
# Numeric vector
numeric_vector <- c(1, 2.5, 4, 8, 10)
print(numeric_vector)
print(class(numeric_vector))

[1]  1.0  2.5  4.0  8.0 10.0
[1] "numeric"


In [ ]:
# Access the first three elements
first_three <- numeric_vector[1:3]
print(first_three)

[1] 1.0 2.5 4.0


In [ ]:
# Character vector
character_vector <- c("apple", "banana", "cherry")
print(character_vector)
print(class(character_vector))

[1] "apple"  "banana" "cherry"
[1] "character"


In [ ]:
# Combine two vectors
combined_vector <- c(numeric_vector, character_vector)
print(combined_vector)

[1] "1"      "2.5"    "4"      "8"      "10"     "apple"  "banana" "cherry"


In [ ]:
# Logical vector
logical_vector <- c(TRUE, FALSE, TRUE, FALSE)
print(logical_vector)
print(class(logical_vector))

[1]  TRUE FALSE  TRUE FALSE
[1] "logical"


In [ ]:
# Vector from 1 to 10
sequence_vector <- 1:10
print(sequence_vector)


 [1]  1  2  3  4  5  6  7  8  9 10


**lists**

In [ ]:
# lists
my_list <- list(
  name = "John Doe",
  age = 30,
  city = "New York",
  is_student = FALSE,
  grades = c(85, 90, 78)
)
print(my_list)

$name
[1] "John Doe"

$age
[1] 30

$city
[1] "New York"

$is_student
[1] FALSE

$grades
[1] 85 90 78



In [ ]:
# Access the age element
my_list[["age"]]

[1] 30

In [ ]:
# Change the city
my_list[["city"]] <- "mdh"

In [ ]:
# nested list
nested_list <- list(
  person1 = list(
    name = "Alice",
    age = 25
  ),
  person2 = list(
    name = "Bob",
    age = 32
  )
)
print(nested_list)

$person1
$person1$name
[1] "Alice"

$person1$age
[1] 25


$person2
$person2$name
[1] "Bob"

$person2$age
[1] 32




**matrices**

In [ ]:
# Create a 3x3 matrix
my_matrix <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3, ncol = 3)
print(my_matrix)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
# rows of matrix
nrow(my_matrix)

[1] 3

In [ ]:
# dim of matrix
dim(my_matrix)

[1] 3 3

In [ ]:
# Access the entire second row
my_matrix[2, ]


[1] 2 5 8

In [ ]:
# Create a 2x4 matrix with data filled by row
my_matrix2 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 2, ncol = 4, byrow = TRUE)
print(my_matrix2)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [ ]:
# Create a 3x3 matrix
my_matrix <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3, ncol = 3)
print(my_matrix)

# Create a matrix with compatible dimensions for addition (e.g., 3x3)
my_matrix2 <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3, ncol = 3)
print(my_matrix2)

# Add two matrices (Now with compatible dimensions)
sum_matrix <- my_matrix + my_matrix2
print(sum_matrix)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18


**creating** **factor**

In [ ]:
# Create a vector of colors
colors <- c("red", "blue", "green", "red", "blue", "green")

In [ ]:
# Convert the vector to a factor
color_factor <- factor(colors)


In [ ]:
# Print the factor
print(color_factor)


[1] red   blue  green red   blue  green
Levels: blue green red


In [ ]:
# View the levels of the factor
levels(color_factor)

[1] "blue"  "green" "red"

**data frame**

In [ ]:
#  Data Frame
student_names <- c("Alice", "Bob", "Charlie")
student_ages <- c(20, 22, 19)
student_grades <- c(85, 90, 78)

In [ ]:
# Create a data frame
student_data <- data.frame(
  Name = student_names,
  Age = student_ages,
  Grade = student_grades
)


In [ ]:
# Print the data frame
print(student_data)

     Name Age Grade
1   Alice  20    85
2     Bob  22    90
3 Charlie  19    78


In [ ]:
# Access specific columns
print(student_data$Name)
print(student_data[ , "Age"])

[1] "Alice"   "Bob"     "Charlie"
[1] 20 22 19


In [ ]:
# Summary of the data frame
summary(student_data)

     Name                Age            Grade      
 Length:3           Min.   :19.00   Min.   :78.00  
 Class :character   1st Qu.:19.50   1st Qu.:81.50  
 Mode  :character   Median :20.00   Median :85.00  
                    Mean   :20.33   Mean   :84.33  
                    3rd Qu.:21.00   3rd Qu.:87.50  
                    Max.   :22.00   Max.   :90.00  

**Arrays**

In [ ]:
# Create a 3-dimensional array
my_array <- array(1:24, dim = c(2, 3, 4))

In [ ]:
# Print the array
print(my_array)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24



In [ ]:
# adding two vectors
vector1 <- c(1, 2, 3)
vector2 <- c(4, 5, 6)

In [ ]:
# Add the vectors
result_vector <- vector1 + vector2

In [ ]:
# Print the result
print(result_vector)

[1] 5 7 9


In [ ]:
# Define the vectors
vector1 <- c(10, 15, 20, 5)
vector2 <- c(3, 5, 7, 2)

In [ ]:
# Calculate the remainder using the modulus operator (%%)
remainder <- vector1 %% vector2

In [ ]:
# Print the result
print(remainder)

[1] 1 0 6 1
